### ISSUE TITLE
Precision Error in Stochastic Universal Selection

### ISSUE THREAD

**Issue by rivalq** [king-11/genx#18]
At a larger population size (~1000), I encountered out of bound panic. So i decided to find the bug behind that. 
```rust
for _ in 0..num_parents {
    while fitness_scale[current_offset] < random_offset {
      current_offset += 1;
    }
    selected_indices.push(current_offset);
    random_offset += fitness_step;
 };
```
I found this code suspicious behind the panic. By printing some values i found out that random_offset was facing precision issues. at ith iteration, `random_offset` should be equal to `initial_random_value + i*fitness_step` but it turns to be greater than that. 

I propose we should use `f64` in our codebase.

**Comment by king-11** [comment]
Fixed by #19
